#!/bin/env bash

# License: GPL v3.0
# JoaoPedroPierri
# @joaoppierri
# Install config i3 script

# Criando diretórios
mkdir $HOME/.joaopp-repo
mkdir $HOME/.compile
mkdir $HOME/.config/rofi
mkdir $HOME/.config/rofi/themes
mkdir $HOME/.config/dunst
mkdir $HOME/.config/nvim
mkdir $HOME/.fonts
mkdir $HOME/.themes
mkdir $HOME/.icons
mkdir $HOME/.Lock
mkdir $HOME/.local/bin
mkdir $HOME/scripts
mkdir $HOME/wallpapers
mkdir $HOME/.config/neofetch

# Aviso
clear && echo 'ATENÇÃO: LEIA O SCRIPT ANTES DE EXECUTA-LO!!!'

echo '
██╗██████╗       ██╗███╗   ██╗███████╗████████╗ █████╗ ██╗     ██╗     
██║╚════██╗      ██║████╗  ██║██╔════╝╚══██╔══╝██╔══██╗██║     ██║     
██║ █████╔╝█████╗██║██╔██╗ ██║███████╗   ██║   ███████║██║     ██║     
██║ ╚═══██╗╚════╝██║██║╚██╗██║╚════██║   ██║   ██╔══██║██║     ██║     
██║██████╔╝      ██║██║ ╚████║███████║   ██║   ██║  ██║███████╗███████╗
╚═╝╚═════╝       ╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚══════╝
                                                                       '
echo
echo 'Pressione enter para continuar'
read

# Atualizando os mirror BR's
sudo pacman -S reflector --noconfirm
sudo reflector -m 5 --save /etc/pacman.d/mirrorlist

# Baixando pacotes
clear && sudo pacman -S git curl wget xorg-xrandr aria2 mpv libnotify viewnior python-pip pacman-contrib gvfs-mtp xdg-user-dirs pulseaudio-alsa w3m ttf-jetbrains-mono ttf-fantasque-sans-mono ttf-fira-code zsh zsh-syntax-highlighting  redshift ttf-font-awesome lib32-dbus-glib imagemagick jq base-devel kitty maim youtube-dl noto-fonts-cjk fzf ueberzug dmenu noto-font noto-fonts-cjk libreoffice zip unzip numlockx mpv brightnessctl dunst usbutils qbittorrent neofetch android-tools gucharmap xorg-xrandr --noconfirm && xdg-user-dirs-update

# Compilações
# Compilando -> Polybar
cd $HOME/.compile
git clone https://aur.archlinux.org/polybar.git
cd $HOME/.compile/polybar
makepkg -sic --noconfirm

# Compilando -> Autotiling
cd $HOME/.compile
git clone https://aur.archlinux.org/autotiling.git
cd $HOME/.compile/autotiling
makepkg -sic --noconfirm

# Compilando -> Pulseaudio-ctl
cd $HOME/.compile
git clone https://aur.archlinux.org/pulseaudio-ctl.git
cd $HOME/.compile/pulseaudio-ctl
makepkg -sic --noconfirm

# Compilando -> scrcpy
cd $HOME/.compile
git clone https://aur.archlinux.org/scrcpy.git
cd $HOME/.compile/scrcpy
makepkg -sic --noconfirm

# Compilando -> Google Chrome
git clone https://aur.archlinux.org/google-chorome.git
cd $HOME/.compile/google-chrome
makepkg -sic --noconfirm

# Clonando meu repositório
cd $HOME/.joaopp-repo
git clone https://github.com/JoaoPedroPierri/dotfiles.git

# dir ~/.local/bin e dando permissões aos scripts
cp $HOME/.joaopp-repo/dotfiles/bin/* $HOME/.local/bin
cd $HOME/.local/bin && chmod +x *

# dir ~/Scripts e dando permissões aos scripts
cp $HOME/.joaopp-repo/dotfiles/scripts/* $HOME/scripts
cd $HOME/scripts && chmod +x *

# Copiando as fontes para o sistema
cp $HOME/.joaopp-repo/dotfiles/fonts/* $HOME/.fonts

# Copiando files zsh
cp ~/.joaopp-repo/dotfiles/.zshrc $HOME
cp ~/.joaopp-repo/dotfiles/.zshenv $HOME
cp ~/.joaopp-repo/dotfiles/.zprofile $HOME
cp ~/.joaopp-repo/dotfiles/.aliases $HOME
touch .zhistory $HOME

# Aplicando tema
# i3
cp $HOME/.joaopp-repo/dotfiles/.config/i3/config $HOME/.config/i3/

# Polybar
cp -r $HOME/.joaopp-repo/dotfiles/.config/polybar/scripts $HOME/.config/polybar
cp $HOME/.joaopp-repo/dotfiles/.config/polybar/config $HOME/.config/polybar
chmod +x $HOME/.config/polybar/scripts/*

# Rofi
sudo pacman -S rofi --noconfirm
cp $HOME/.joaopp-repo/dotfiles/.config/rofi/drun.rasi $HOME/.config/rofi/
cp $HOME/.joaopp-repo/dotfiles/.config/rofi/themes/dark.rasi $HOME/.config/rofi/themes/

# Kitty
cp $HOME/.joaopp-repo/dotfiles/.config/kitty/kitty.conf $HOME/.config/kitty
cp $HOME/.joaopp-repo/dotfiles/.config/kitty/theme.conf $HOME/.config/kitty
sudo ln -sv /usr/bin/kitty /usr/bin/xterm

# DUNST
cp $HOME/.joaopp-repo/dotfiles/.config/dunst/dunstrc $HOME/.config/dunst

# NITROGEN
sudo pacman -S nitrogen --noconfirm
cd $HOME/wallpapers
cp $HOME/.joaopp/dotfiles/wallpapers/* #HOME/wallpapers
nitrogen --set-auto $HOME/wallpapers/8.png

# NeoVIM
cp $HOME/.joaopp-repo/dotfiles/.config/nvim/init.vim $HOME/.config/nvim

# Neofetch
sudo pacman -S neofetch --noconfirm
cp $HOME/.joaopp-repo/dotfiles/.config/neofetch/config.conf ~/.config/neofetch

# i3 Lock
sudo pacman -S fortune-mod maim i3lock --noconfirm
cp $HOME/.joaopp-repo/dotfiles/lock/ArchLinux.png $HOME/.Lock

# Restart i3
i3-msg restart
